// stubs/inertia/react/resources/js/pages/auth/login.tsx
import InputError from '@/components/input-error';
import TextLink from '@/components/text-link';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AuthLayout from '@/layouts/auth-layout';
import { register } from '@/routes';
import { request } from '@/routes/password';
import { Head, useForm } from '@inertiajs/react';
import { LoaderCircle } from 'lucide-react';
import axios from 'axios';
import { useEffect, useState } from 'react';
import { startAuthentication, browserSupportsWebAuthn } from '@simplewebauthn/browser';
import passkeysTwoFactor from '@/routes/passkeys-two-factor';
import * as loginRoute from '@/routes/login';

interface LoginProps {
    status?: string;
    canResetPassword: boolean;
    canUsePasskeys: boolean;
}

interface loginForm {
    email: string;
    password: string;
    passkey: string;
    [key: string]: string | undefined;
}

export default function Login({ status, canResetPassword, canUsePasskeys }: LoginProps) {

    const loginForm = useForm<loginForm>({
        email: "",
        password: "",
        passkey: ""
    })

    const [showPassword, setShowPassword] = useState<boolean>(true);

    const submit = async (e:React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        authenticate();
    }

    const authenticate = async () => {
        if (canUsePasskeys && showPassword) {
            loginForm.post(loginRoute.store().url, {
                onSuccess: () => loginForm.reset('password')
            })
        } else {
            if (! browserSupportsWebAuthn()) {
                loginForm.setError('passkey', "Your Browser Dosen't support passkeys");
                return;
            }
            const options = await axios.get(passkeysTwoFactor.authenticateOptions().url, {
                params: {
                    email: loginForm.data.email
                }
            })
    
            try {
                const passkey = await startAuthentication({
                    optionsJSON: options.data
                });

                loginForm.setData('passkey', JSON.stringify(passkey));
                
            } catch (error) {
                loginForm.setError('passkey', "Passkey login failed. please try again.");
                console.error(error);
            }
        }
    }

    useEffect(()=>{
        if (showPassword === false)
            authenticate();
        loginForm.clearErrors();
    },[showPassword])

    useEffect(()=>{
        if (loginForm.data.passkey !== "") { 
            loginForm.post(passkeysTwoFactor.authenticate().url, {
                onSuccess: () => loginForm.reset('password')
            })
        };
    }, [loginForm.data.passkey]);

    
    return (
        <AuthLayout title="Log in to your account" description="Enter your email and password below to log in">
            <Head title="Log in" />

            <form onSubmit={submit} className="flex flex-col gap-6">
                <div className="grid gap-6">
                    <div className="grid gap-2">
                        <Label htmlFor="email">Email address</Label>
                        <Input
                            id="email"
                            type="email"
                            name="email"
                            required
                            autoFocus
                            tabIndex={1}
                            autoComplete="email"
                            placeholder="email@example.com"
                            onChange={(e) => loginForm.setData('email', e.target.value)}
                        />
                        <InputError message={loginForm.errors.email} />
                        <InputError message={loginForm.errors.passkey} />
                        <InputError message={loginForm.errors.attempts} />
                    </div>

                    {showPassword && (
                        <div className="grid gap-2">
                            <div className="flex items-center">
                                <Label htmlFor="password">Password</Label>
                                {canResetPassword && (
                                    <TextLink href={request()} className="ml-auto text-sm" tabIndex={5}>
                                        Forgot password?
                                    </TextLink>
                                )}
                            </div>
                            <Input
                                id="password"
                                type="password"
                                name="password"
                                required
                                tabIndex={2}
                                autoComplete="current-password"
                                placeholder="Password"
                                onChange={(e) => loginForm.setData('password', e.target.value)}
                            />
                            <InputError message={loginForm.errors.password} />
                        </div>
                    )}

                    <div className="flex items-center space-x-3">
                        <Checkbox id="remember" name="remember" tabIndex={3} />
                        <Label htmlFor="remember">Remember me</Label>
                    </div>

                    <Button type="submit" className="mt-4 w-full" tabIndex={4} disabled={loginForm.processing}>
                        {loginForm.processing && <LoaderCircle className="h-4 w-4 animate-spin" />}
                        Log in
                    </Button>

                    {canUsePasskeys && (
                        <Button onClick={()=>setShowPassword(!showPassword)} type="button" variant={"secondary"} className="w-full" tabIndex={4} disabled={loginForm.processing}>
                            {showPassword ? (<>
                                Use Passkey
                            </>) : (<>
                                Use Password
                            </>)}
                        </Button>
                    )}
                    
                </div>

                <div className="text-center text-sm text-muted-foreground">
                    Don't have an account?{' '}
                    <TextLink href={register()} tabIndex={5}>
                        Sign up
                    </TextLink>
                </div>
            </form>

            {status && <div className="mb-4 text-center text-sm font-medium text-green-600">{status}</div>}
        </AuthLayout>
    );
}

// stubs/inertia/vue/resources/js/pages/auth/Login.vue
<script setup lang="ts">
import InputError from '@/components/InputError.vue';
import TextLink from '@/components/TextLink.vue';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AuthBase from '@/layouts/AuthLayout.vue';
import { register } from '@/routes';
import { request } from '@/routes/password';
import { Head, useForm } from '@inertiajs/vue3';
import { LoaderCircle } from 'lucide-vue-next';
import { nextTick, ref, watch } from 'vue';
import axios from 'axios';
import { startAuthentication, browserSupportsWebAuthn } from '@simplewebauthn/browser';
import passkeysTwoFactor from '@/routes/passkeys-two-factor';
import * as loginRoute from '@/routes/login';

const props = defineProps<{
    status?: string;
    canResetPassword: boolean;
    canUsePasskeys: boolean;
}>();

interface loginForm {
    email: string;
    password: string;
    passkey: string;
    [key: string]: string | undefined;
}

const loginForm = useForm<loginForm>({
    email: "",
    password: "",
    passkey: ""
})

const showPassword = ref<boolean>(true);

const submit = () => {
    authenticate();
}

const authenticate = async () => {
    if (props.canUsePasskeys && showPassword.value) {
        loginForm.post(loginRoute.store().url, {
            onSuccess: () => loginForm.reset('password')
        })
    } else {
        if (! browserSupportsWebAuthn()) {
            loginForm.setError('passkey', "Your Browser Dosen't support passkeys");
            return;
        }
        const options = await axios.get(passkeysTwoFactor.authenticateOptions().url, {
            params: {
                email: loginForm.email
            }
        })

        try {
            const passkey = await startAuthentication({
                optionsJSON: options.data
            });

            loginForm.passkey = JSON.stringify(passkey);

            await nextTick();

            loginForm.post(passkeysTwoFactor.authenticate().url, {
                onSuccess: () => loginForm.reset('password')
            });
        } catch (error) {
            loginForm.setError('passkey', "Passkey login failed. please try again.");
            console.error(error);
        }
    }
}

watch(showPassword, (value)=>{
    if (value === false)
        authenticate();
    loginForm.clearErrors();
});

</script>

<template>
    <AuthBase
        title="Log in to your account"
        description="Enter your email and password below to log in"
    >
        <Head title="Log in" />

        <div
            v-if="status"
            class="mb-4 text-center text-sm font-medium text-green-600"
        >
            {{ status }}
        </div>

        <form @submit.prevent="submit" class="flex flex-col gap-6">
            <div class="grid gap-6">
                <div class="grid gap-2">
                    <Label htmlFor="email">Email address</Label>
                    <Input
                        id="email"
                        type="email"
                        name="email"
                        required
                        autofocus
                        :tabindex="1"
                        autocomplete="email"
                        placeholder="email@example.com"
                        v-model="loginForm.email"
                    />
                    <InputError :message="loginForm.errors.email" />
                    <InputError :message="loginForm.errors.passkey" />
                    <InputError :message="loginForm.errors.attempts" />
                </div>

                <div v-if="showPassword" class="grid gap-2">
                    <div class="flex items-center justify-between">
                        <Label for="password">Password</Label>
                        <TextLink
                            v-if="canResetPassword"
                            :href="request()"
                            class="text-sm"
                            :tabindex="5"
                        >
                            Forgot password?
                        </TextLink>
                    </div>
                    <Input
                        id="password"
                        type="password"
                        name="password"
                        required
                        :tabindex="2"
                        autocomplete="current-password"
                        placeholder="Password"
                        v-model="loginForm.password"
                    />
                    <InputError :message="loginForm.errors.password" />
                </div>

                <div class="flex items-center justify-between">
                    <Label for="remember" class="flex items-center space-x-3">
                        <Checkbox id="remember" name="remember" :tabindex="3" />
                        <span>Remember me</span>
                    </Label>
                </div>

                <Button
                    type="submit"
                    class="mt-4 w-full"
                    :tabindex="4"
                    :disabled="loginForm.processing"
                    data-test="login-button"
                >
                    <LoaderCircle
                        v-if="loginForm.processing"
                        class="h-4 w-4 animate-spin"
                    />
                    Log in
                </Button>

                <Button
                    v-if="canUsePasskeys"
                    type="button" 
                    variant="secondary" 
                    class="w-full" 
                    :tabindex="4"
                    :disabled="loginForm.processing"
                    @click="()=>{showPassword = !showPassword}"
                >
                    {{ showPassword ? 'Use Passkey' : 'Use Password' }}
                </Button>
            </div>

            <div class="text-center text-sm text-muted-foreground">
                Don't have an account?
                <TextLink :href="register()" :tabindex="5">Sign up</TextLink>
            </div>
        </form>
    </AuthBase>
</template>
